name: Dockerfile.dockerfile

on: [push]

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v2
    - name: Docker file image
      run: docker build -f Dockerfile.dockerfile .\
    - name: Building container
      run: docker run --name dockercontainer Dockerimage
    - name: Copying main.exe
      run: docker cp dockercontainer:/praktyki-wp-2023-ropzenn/dist/main.exe ${PWD}

    - name: Create Github release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload release asset   
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./main.exe
        asset_name: main-v${{ github.run_number }}.exe
        asset_content_type: application/octet-stream
