name: Dockerfile.dockerfile

on: [push]

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Docker file image
      run: docker build -f Dockerfile.dockerfile .\
    - name: pyinstaller 
      run: pip install pyinstaller  
    - name: req
      run: pip install -r requirements.txt
    - name: build .exe
      run: pyinstaller --onefile main.py

    - name: Download a single artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: main
        path: D:\a\praktyki-wp-2023-ropzenn\praktyki-wp-2023-ropzenn\dist\main.exe
